### ISSUE TITLE
Simple Diffie-Hellman computation fails.

### ISSUE THREAD

**Issue by shumy-tools** [str4d/ed25519-java#80]
A simple computation as:
```
final FieldElement nodeSecret = Utils.getRandomFieldElement();
final GroupElement nodeKey = Utils.basePoint.scalarMultiply(nodeSecret.toByteArray());
    
final FieldElement termSecret = Utils.getRandomFieldElement();
final GroupElement termKey = Utils.basePoint.scalarMultiply(termSecret.toByteArray());
    
nodeKey.scalarMultiply(termSecret.toByteArray());
```

Fails with:
```
Exception in thread "main" java.lang.NullPointerException
at net.i2p.crypto.eddsa.math.GroupElement.select(GroupElement.java:930)
at net.i2p.crypto.eddsa.math.GroupElement.scalarMultiply(GroupElement.java:964)
at AOTMainTest.main(AOTMainTest.java:26)
```

**Comment by str4d** [comment]
I'll have a brief look into this at some point, but I recommend using `curve25519-elisabeth` for these kinds of computations: https://github.com/cryptography-cafe/curve25519-elisabeth
